events {
    worker_connections 1024;
}

http {
    upstream strongbox {
        server node1:8200;
        server node2:8200;
        server node3:8200;
    }

    server {
        listen 80;
        server_name yaat-strongbox.duckdns.org;

        location / {
            proxy_pass http://strongbox;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
        }
    }
}
