events {}

http {
    upstream strongbox {
        server node1:8080;
        server node2:8080;
        server node3:8080;
    }

    server {
        listen 80;
        server_name yaat-strongbox.duckdns.org;

        location / {
            proxy_pass http://strongbox;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
          
        }
    }
}
